Drop database rideflow;
Create database if not exists RideFlow;
use RideFlow;
-- 1. User Table
CREATE TABLE User (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    Full_Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role           ENUM('Admin','Rider','Driver') NOT NULL,
    Phone_Number VARCHAR(20) UNIQUE,
    accountStatus ENUM('Active', 'Suspended', 'Banned', 'Flagged') DEFAULT 'Active',  -- enum means that this attribute can only have value from these three options
    CreatedOn DATETIME DEFAULT CURRENT_TIMESTAMP -- automatically input current date and time
);

-- 2. Driver Table (child of user)
CREATE TABLE Driver (
    driver_id INT PRIMARY KEY,
    Licence_No VARCHAR(50) NOT NULL UNIQUE,
    CNIC VARCHAR(20) NOT NULL UNIQUE,
    Profile_pic VARCHAR(255),
    Verification_Status ENUM('Pending', 'Verified', 'Rejected') DEFAULT 'Pending',
    Availability_Status ENUM('Offline', 'Online', 'On trip') DEFAULT 'Offline',
    Total_Trips INT DEFAULT 0 CHECK (Total_Trips >= 0),
    Average_Rating DECIMAL(3,2) DEFAULT 0.00 CHECK (Average_Rating BETWEEN 0 AND 5),  -- between 0.0 to 5.0
    CONSTRAINT fk_driver_user FOREIGN KEY (driver_id) REFERENCES User(user_id) ON DELETE CASCADE -- driverid is userid in user table. if user deleted, driver also deleted
);

-- 3. Rider Table (child of user)
CREATE TABLE Rider (
    rider_id INT PRIMARY KEY,
    Average_Rating DECIMAL(3,2) DEFAULT 0.00 CHECK (Average_Rating BETWEEN 0 AND 5),
    CONSTRAINT fk_rider_user FOREIGN KEY (rider_id) REFERENCES User(user_id) ON DELETE CASCADE  -- riderid is userid in user table. if user deleted, rider also deleted
);

-- 4. Admin Table (Specialization of User)
CREATE TABLE Admin (
    AdminID INT PRIMARY KEY,
    CONSTRAINT fk_admin_user FOREIGN KEY (AdminID) REFERENCES User(user_id) ON DELETE CASCADE -- adminid is userid in usertable. if user deleted, admin also deleted
);

-- 5. Vehicle Table
CREATE TABLE Vehicle (
    vehicle_id INT AUTO_INCREMENT PRIMARY KEY,
    driver_id INT NOT NULL,   -- each vehicle has exactly one driver
    make VARCHAR(50) NOT NULL,
    Model VARCHAR(50) NOT NULL,
    Color VARCHAR(30),
    License_Plate VARCHAR(20) NOT NULL UNIQUE,
	vehicle_type        ENUM('Economy','Premium','Bike') NOT NULL,
    Verification_Status ENUM('Pending', 'Verified', 'Rejected') DEFAULT 'Pending',
    year                YEAR        NOT NULL,
	CONSTRAINT check_vehicle_year   CHECK       (year >= 1990 AND year <= 2026),
    CONSTRAINT fk_vehicle_driver FOREIGN KEY (driver_id) REFERENCES Driver(driver_id) ON DELETE CASCADE -- id driver deleted, vehicle also deleted
);

-- 6. Location Table
CREATE TABLE Location (
    location_id INT AUTO_INCREMENT PRIMARY KEY,
    Address TEXT NOT NULL,
    Latitude DECIMAL(10, 8) NOT NULL,
    Longitude DECIMAL(11, 8) NOT NULL,
    City VARCHAR(50) NOT NULL,
    Country VARCHAR(50) NOT NULL,
	CONSTRAINT check_location_latitude  CHECK       (latitude  BETWEEN -90.0000000  AND  90.0000000),
    CONSTRAINT check_location_longitude CHECK       (longitude BETWEEN -180.0000000 AND 180.0000000)
);

-- 7. PromoCode Table
CREATE TABLE PromoCode (
    promo_id INT AUTO_INCREMENT PRIMARY KEY,
    AdminID INT NOT NULL, -- generated by one and only admin
    Code VARCHAR(20) NOT NULL UNIQUE,
    Discount_Type ENUM('Percentage', 'Flat') NOT NULL,
    Discount_Value DECIMAL(10, 2) NOT NULL CHECK (Discount_Value > 0),
    Usage_Limit INT DEFAULT 1 CHECK (Usage_Limit > 0),
    usage_count    INT           NOT NULL DEFAULT 0,
    Expiry_Date DATETIME NOT NULL,
    Min_Fare DECIMAL(10, 2) DEFAULT 0.00 CHECK (min_fare >= 0),
    CONSTRAINT fk_promo_admin FOREIGN KEY (AdminID) REFERENCES Admin(AdminID)  -- admin generates promocode, even if admin is deleted, promocode remains
);

CREATE TABLE FarePricing (
    pricing_id      INT AUTO_INCREMENT PRIMARY KEY,
    city            VARCHAR(100) NOT NULL,
    vehicle_type    ENUM('Economy','Premium','Bike') NOT NULL,
    base_rate       DECIMAL(10,2) NOT NULL,
    per_km_rate     DECIMAL(10,2) NOT NULL,
    per_minute_rate DECIMAL(10,2) NOT NULL,
    surge_multiplier DECIMAL(4,2) DEFAULT 1.00
);
-- 8. Rides Table
CREATE TABLE Rides (
    ride_id INT AUTO_INCREMENT PRIMARY KEY,
    rider_id INT NOT NULL,  -- every ride has exactly one rider
    driver_id INT, -- NULL if no driver accepts
    vehicle_id INT, -- NULL if no driver accepts
    pickup_loc_id INT NOT NULL,
    drop_loc_id INT NOT NULL,
    Ride_Status ENUM('Requested', 'Accepted', 'Driver En route','In progress', 'Completed', 'Cancelled') DEFAULT 'Requested',
    Fare DECIMAL(10, 2) CHECK (Fare >= 0),
    Distance DECIMAL(10, 2) COMMENT 'Distance in KM',
    Duration_in_minutes Int CHECK (Duration_in_minutes >=0),
    Scheduled_At DATETIME,
    Requested_At DATETIME DEFAULT CURRENT_TIMESTAMP,
    Started_At DATETIME,
    End_Time DATETIME,
        CONSTRAINT fk_rides_rider     FOREIGN KEY (rider_id)
        REFERENCES Rider(rider_id)
        ON DELETE RESTRICT ON UPDATE CASCADE, -- cant delete a rider if his rides exist, if rider id updated in rider, also update in rides
    CONSTRAINT fk_rides_driver    FOREIGN KEY (driver_id)
        REFERENCES Driver(driver_id)
        ON DELETE SET NULL ON UPDATE CASCADE, -- if driver deleted set NULL here, if updated update here too
    CONSTRAINT fk_rides_vehicle   FOREIGN KEY (vehicle_id)
        REFERENCES Vehicle(vehicle_id)
        ON DELETE SET NULL ON UPDATE CASCADE,   -- if vehicle deleted set NULL, if updated update here too
    CONSTRAINT fk_rides_pickup    FOREIGN KEY (pickup_loc_id)
        REFERENCES Location(location_id)
        ON DELETE RESTRICT ON UPDATE CASCADE, -- cant delete a location if it is being used in rides, if updated update here too
    CONSTRAINT fk_rides_drop      FOREIGN KEY (drop_loc_id)
        REFERENCES Location(location_id)
        ON DELETE RESTRICT ON UPDATE CASCADE  -- cant delete a location if it is being used in rides, if updated update here too
);


-- 9. Payment Table
CREATE TABLE Payment (
    payment_id INT AUTO_INCREMENT PRIMARY KEY,
    rider_id INT NOT NULL, -- payment made by exactly one rider
    ride_id INT NOT NULL UNIQUE,  -- payment made for exactly one unique ride
    promo_id INT, -- NULL if not used
    Amount DECIMAL(10, 2) NOT NULL CHECK (Amount >= 0),
    Status ENUM('Pending', 'Completed', 'Failed','Refunded') DEFAULT 'Pending',
    Date DATETIME DEFAULT CURRENT_TIMESTAMP,
    Method ENUM('Cash', 'Credit Card', 'Wallet') NOT NULL,
	CONSTRAINT fk_payment_ride      FOREIGN KEY (ride_id)
        REFERENCES Rides(ride_id)
        ON DELETE CASCADE ON UPDATE CASCADE, -- cant delete a ride if payments exist
    CONSTRAINT fk_payment_rider     FOREIGN KEY (rider_id)
        REFERENCES Rider(rider_id)
        ON DELETE RESTRICT ON UPDATE CASCADE, -- cant delete a rider if payments exist
    CONSTRAINT fk_payment_promo     FOREIGN KEY (promo_id)
        REFERENCES PromoCode(promo_id)
        ON DELETE SET NULL ON UPDATE CASCADE --  if promo deleted, set null here
);

-- 10. Complaints Table
CREATE TABLE Complaints (
    complaint_id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    ride_id INT ,
    Description TEXT NOT NULL,
    Status ENUM('Open', 'In-Progress', 'Resolved') DEFAULT 'Open',
    FiledBy_UserType ENUM('Rider', 'Driver') NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_comp_user FOREIGN KEY (user_id) REFERENCES User(user_id) ON DELETE CASCADE ON UPDATE CASCADE, -- if user deleted complaint deleted
    CONSTRAINT fk_comp_ride FOREIGN KEY (ride_id) REFERENCES Rides(ride_id) ON DELETE SET NULL ON UPDATE CASCADE -- can be linked to no ride and even if ride deleted, complaint exists
);

-- 11. Rating Table
CREATE TABLE Rating (
    rating_id INT AUTO_INCREMENT PRIMARY KEY,
    ride_id INT NOT NULL,
    rated_user_id INT NOT NULL,
    rated_by_user_id INT NOT NULL,
    Score INT NOT NULL CHECK (Score BETWEEN 1 AND 5),
    Comment TEXT,
    RatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT uq_rating_per_ride_user UNIQUE      (ride_id, rated_by_user_id), -- for a ride, driver/rider can make rating only one time
	CONSTRAINT fk_rating_ride          FOREIGN KEY (ride_id)
        REFERENCES Rides(ride_id)
        ON DELETE CASCADE ON UPDATE CASCADE, -- if ride deleted, rating deleted
    CONSTRAINT fk_rating_rated_by      FOREIGN KEY (rated_by_user_id)
        REFERENCES User(user_id)
        ON DELETE CASCADE ON UPDATE CASCADE, -- if user who rated deleted, rating deleted
    CONSTRAINT fk_rating_rated_user    FOREIGN KEY (rated_user_id)
        REFERENCES User(user_id)
        ON DELETE CASCADE ON UPDATE CASCADE -- if user who was rated deleted, rating deleted
);
-- 12.Ride History
CREATE TABLE RideHistory (
    history_id    INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ride_id       INT NOT NULL, 
    rider_id      INT NOT NULL,
    driver_id     INT NULL,
    vehicle_id    INT NULL,
    pickup_loc_id INT NOT NULL,
    drop_loc_id   INT NOT NULL,
    final_status  ENUM('Completed','Cancelled') NOT NULL,
    fare          DECIMAL(10,2) NULL,
    distance      DECIMAL(10,2) NULL,
    Duration_in_minutes      INT NULL,
    requested_at  DATETIME NOT NULL,
    started_at    DATETIME NULL,
    end_time      DATETIME NULL,
    archived_at   DATETIME DEFAULT CURRENT_TIMESTAMP,
 -- ride transferred from ride table to here when cancelled or completed
	CONSTRAINT fk_hrides_rider     FOREIGN KEY (rider_id)
        REFERENCES Rider(rider_id),
    CONSTRAINT fk_hrides_driver    FOREIGN KEY (driver_id)
        REFERENCES Driver(driver_id)
        ON DELETE SET NULL ON UPDATE CASCADE, -- if driver deleted set NULL here, if updated update here too
    CONSTRAINT fk_hrides_vehicle   FOREIGN KEY (vehicle_id)
        REFERENCES Vehicle(vehicle_id)
        ON DELETE SET NULL ON UPDATE CASCADE,   -- if vehicle deleted set NULL, if updated update here too
    CONSTRAINT fk_hrides_pickup    FOREIGN KEY (pickup_loc_id)
        REFERENCES Location(location_id)
        ON DELETE RESTRICT ON UPDATE CASCADE, -- cant delete a location if it is being used in rides, if updated update here too
    CONSTRAINT fk_hrides_drop      FOREIGN KEY (drop_loc_id)
        REFERENCES Location(location_id)
        ON DELETE RESTRICT ON UPDATE CASCADE  -- cant delete a location if it is being used in rides, if updated update here too
);
-- 13. Wallet (online for any user)
CREATE TABLE Wallet (
    wallet_id INT AUTO_INCREMENT PRIMARY KEY,
    user_id   INT NOT NULL UNIQUE,
    balance   DECIMAL(12,2) DEFAULT 0.00,
    CONSTRAINT fk_wallet_user FOREIGN KEY (user_id) REFERENCES User(user_id) ON DELETE CASCADE
);
-- 14. DriverEarning history
CREATE TABLE DriverEarnings (
    earning_id        INT AUTO_INCREMENT PRIMARY KEY,
    driver_id         INT NOT NULL,
    ride_id           INT NOT NULL UNIQUE,
    gross_amount      DECIMAL(10,2) NOT NULL,
    commission_amount DECIMAL(10,2) NOT NULL,
    net_amount        DECIMAL(10,2) NOT NULL,
    CONSTRAINT fk_earnings_driver FOREIGN KEY (driver_id) REFERENCES Driver(driver_id),
    CONSTRAINT fk_earnings_ride   FOREIGN KEY (ride_id)   REFERENCES Rides(ride_id)
);

CREATE TABLE AdminNotification (
    notification_id INT AUTO_INCREMENT PRIMARY KEY,
    message         TEXT NOT NULL,
    related_user_id INT NULL,
    is_read         BOOL DEFAULT FALSE,  
    created_at      DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notif_user FOREIGN KEY (related_user_id) REFERENCES User(user_id) ON DELETE SET NULL
);

CREATE TABLE PayoutRequest (
    payout_id    INT AUTO_INCREMENT PRIMARY KEY,
    driver_id    INT NOT NULL,
    amount       DECIMAL(10,2) NOT NULL,
    status       ENUM('Pending','Approved','Rejected','Paid') DEFAULT 'Pending',
    requested_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    processed_at DATETIME,
    CONSTRAINT fk_payout_driver FOREIGN KEY (driver_id) REFERENCES Driver(driver_id)
);

-- process to calculate fare pricing
DELIMITER $$

CREATE PROCEDURE sp_CalculateFare(
    IN  p_city          VARCHAR(100),
    IN  p_vehicle_type  ENUM('Economy','Premium','Bike'),
    IN  p_distance_km   DECIMAL(10,2),
    IN  p_duration_min  INT,
    IN  p_is_surge      TINYINT, -- 1 for active surge, 0 for normal
    OUT p_final_fare    DECIMAL(10,2)
)
BEGIN
    DECLARE v_base_rate DECIMAL(10,2);
    DECLARE v_per_km    DECIMAL(10,2);
    DECLARE v_per_min   DECIMAL(10,2);
    DECLARE v_surge     DECIMAL(4,2);

    -- Lookup rates from FarePricing table
    SELECT base_rate, per_km_rate, per_minute_rate, surge_multiplier
    INTO   v_base_rate, v_per_km, v_per_min, v_surge
    FROM   FarePricing
    WHERE  city = p_city AND vehicle_type = p_vehicle_type
    ORDER BY pricing_id DESC LIMIT 1;

    -- Formula 
    SET p_final_fare = v_base_rate + (v_per_km * p_distance_km) + (v_per_min * p_duration_min);

    -- Apply Surge 
    IF p_is_surge = 1 THEN
        SET p_final_fare = p_final_fare * v_surge;
    END IF;

    SET p_final_fare = ROUND(p_final_fare, 2);
END$$

DELIMITER ;

-- completed/cancelled rides move to ridehistory
DELIMITER $$

CREATE TRIGGER trg_ArchiveFinishedRide
AFTER UPDATE ON Rides
FOR EACH ROW
BEGIN
    -- Move to history only if status changes to Completed or Cancelled 
    IF (NEW.Ride_Status IN ('Completed', 'Cancelled')) 
       AND (OLD.Ride_Status NOT IN ('Completed', 'Cancelled')) THEN
        
        INSERT INTO RideHistory (
            ride_id, rider_id, driver_id, vehicle_id, pickup_loc_id, 
            drop_loc_id, final_status, fare, distance, Duration_in_minutes, 
            requested_at, started_at, end_time
        ) VALUES (
            NEW.ride_id, NEW.rider_id, NEW.driver_id, NEW.vehicle_id, NEW.pickup_loc_id, 
            NEW.drop_loc_id, NEW.Ride_Status, NEW.Fare, NEW.Distance, NEW.Duration_in_minutes, 
            NEW.Requested_At, NEW.Started_At, NEW.End_Time
        );
    END IF;
END$$

DELIMITER ;

-- flag if rider rating below 3.0
DELIMITER $$

CREATE TRIGGER trg_UpdateRiderAndFlag
AFTER INSERT ON Rating
FOR EACH ROW
BEGIN
    DECLARE v_avg DECIMAL(3,2);
    DECLARE v_role ENUM('Admin','Rider','Driver');

    -- Identify if the rated user is a Rider
    SELECT role INTO v_role FROM User WHERE user_id = NEW.rated_user_id;

    IF v_role = 'Rider' THEN
        -- Recalculate Average 
        SELECT AVG(Score) INTO v_avg FROM Rating WHERE rated_user_id = NEW.rated_user_id;

        -- Update Rider Table
        UPDATE Rider SET average_rating = v_avg WHERE rider_id = NEW.rated_user_id;

        -- Flag if below 3.0 
        IF v_avg < 3.0 THEN
            UPDATE User SET accountStatus = 'Flagged' WHERE user_id = NEW.rated_user_id;
            
            INSERT INTO AdminNotification (message, related_user_id)
            VALUES (CONCAT('Rider Quality Warning: Rider ID ', NEW.rated_user_id, ' rating is ', v_avg), NEW.rated_user_id);
        END IF;
    END IF;
END$$

DELIMITER ;

-- flag driver if average rating falls below 3.5
DELIMITER $$

CREATE TRIGGER trg_UpdateDriverAndFlag
AFTER INSERT ON Rating
FOR EACH ROW
BEGIN
    DECLARE v_avg DECIMAL(3,2);
    DECLARE v_role ENUM('Admin','Rider','Driver');

    -- Identify if the rated user is a Driver
    SELECT role INTO v_role FROM User WHERE user_id = NEW.rated_user_id;

    IF v_role = 'Driver' THEN
        -- Recalculate Average 
        SELECT AVG(Score) INTO v_avg FROM Rating WHERE rated_user_id = NEW.rated_user_id;

        -- Update Driver Table
        UPDATE Driver SET Average_Rating = v_avg WHERE driver_id = NEW.rated_user_id;

        -- Flag if below 3.5
        IF v_avg < 3.5 THEN
            UPDATE User SET accountStatus = 'Flagged' WHERE user_id = NEW.rated_user_id;
            
            INSERT INTO AdminNotification (message, related_user_id)
            VALUES (CONCAT('Low Rating Alert: Driver ID ', NEW.rated_user_id, ' has dropped to ', v_avg), NEW.rated_user_id);
        END IF;
    END IF;
END$$

DELIMITER ;
-- If paid through wallet, deduction
DELIMITER $$

CREATE TRIGGER trg_ProcessWalletPayment
BEFORE INSERT ON Payment
FOR EACH ROW
BEGIN
    IF NEW.Method = 'Wallet' THEN
        -- Ensure rider has enough balance 
        IF (SELECT balance FROM Wallet WHERE user_id = NEW.rider_id) < NEW.Amount THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Insufficient wallet balance for this payment.';
        ELSE
            -- Deduct amount from Rider's wallet
            UPDATE Wallet 
            SET balance = balance - NEW.Amount 
            WHERE user_id = NEW.rider_id;
        END IF;
    END IF;
END$$

DELIMITER ;
-- Manage creadits to Drivers wallet
DELIMITER $$
CREATE TRIGGER trg_CreditDriverWallet
AFTER INSERT ON DriverEarnings
FOR EACH ROW
BEGIN
    UPDATE Wallet 
    SET balance = balance + NEW.net_amount 
    WHERE user_id = NEW.driver_id;
END$$
DELIMITER ;

DELIMITER $$
-- deduct commision
CREATE TRIGGER trg_GenerateEarningsOnCompletion
AFTER UPDATE ON Rides
FOR EACH ROW
BEGIN
    -- Only trigger when a ride is completed
    IF NEW.Ride_Status = 'Completed' AND OLD.Ride_Status <> 'Completed' THEN
        -- Check if a fare was calculated/set
        IF NEW.Fare IS NOT NULL AND NEW.Fare > 0 THEN
            INSERT INTO DriverEarnings (
                driver_id, 
                ride_id, 
                gross_amount, 
                commission_amount, 
                net_amount
            )
            VALUES (
                NEW.driver_id, 
                NEW.ride_id, 
                NEW.Fare, 
                NEW.Fare * 0.20, -- Platform takes 20% commission
                NEW.Fare * 0.80  -- Driver receives 80% net earning
            );
        END IF;
    END IF;
END$$

DELIMITER ;
-- dont let ride get accepted by unverified vehicle
DELIMITER $$
CREATE TRIGGER trg_VerifyVehicleForRide
BEFORE UPDATE ON Rides
FOR EACH ROW
BEGIN
    IF NEW.Ride_Status = 'Accepted' THEN
        IF (SELECT Verification_Status FROM Vehicle WHERE vehicle_id = NEW.vehicle_id) != 'Verified' THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Only verified vehicles can accept rides.';
        END IF;
    END IF;
END$$
DELIMITER ;
-- if ride accepted by driver, driver is on trip
DELIMITER $$
CREATE TRIGGER trg_RideAccepted
AFTER UPDATE ON Rides
FOR EACH ROW
BEGIN
    IF NEW.Ride_Status = 'Accepted' AND OLD.Ride_Status = 'Requested' THEN
        UPDATE Driver SET Availability_Status = 'On trip' WHERE driver_id = NEW.driver_id;
    END IF;
END$$
DELIMITER ;
-- when ride is completed rider becomes online again
DELIMITER $$
CREATE TRIGGER trg_RideCompleted
AFTER UPDATE ON Rides
FOR EACH ROW
BEGIN
    IF NEW.Ride_Status = 'Completed' AND OLD.Ride_Status != 'Completed' THEN
        UPDATE Driver 
        SET Availability_Status = 'Online',
            Total_Trips = Total_Trips + 1
        WHERE driver_id = NEW.driver_id;
    END IF;
END$$
DELIMITER ;
-- when ride is cancelled rider becomes online again
DELIMITER $$
CREATE TRIGGER trg_RideCancelled
AFTER UPDATE ON Rides
FOR EACH ROW
BEGIN
    IF NEW.Ride_Status = 'Cancelled' AND OLD.Ride_Status NOT IN ('Completed','Cancelled') THEN
        IF NEW.driver_id IS NOT NULL THEN
            UPDATE Driver SET Availability_Status = 'Online' WHERE driver_id = NEW.driver_id;
        END IF;
    END IF;
END$$
DELIMITER ;
-- promocode usage count and limit
DELIMITER $$
CREATE TRIGGER trg_IncrementPromoUsage
BEFORE INSERT ON Payment
FOR EACH ROW
BEGIN
    IF NEW.promo_id IS NOT NULL THEN
        IF (SELECT usage_count FROM PromoCode WHERE promo_id = NEW.promo_id) >= 
           (SELECT Usage_Limit FROM PromoCode WHERE promo_id = NEW.promo_id) THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Promo code usage limit reached.';
        END IF;
        UPDATE PromoCode SET usage_count = usage_count + 1 WHERE promo_id = NEW.promo_id;
    END IF;
END$$
DELIMITER ;
-- create view for revenue by city reporting
CREATE OR REPLACE VIEW vw_RevenueByCity AS
SELECT 
    l.City, p.Date AS payment_date,
    COUNT(r.ride_id) AS Total_Rides,
    SUM(p.Amount) AS Gross_Revenue,
    SUM(de.commission_amount) AS Platform_Commission
FROM Rides r
JOIN Payment p ON r.ride_id = p.ride_id
JOIN DriverEarnings de ON r.ride_id = de.ride_id
JOIN Location l ON r.pickup_loc_id = l.location_id
WHERE r.Ride_Status = 'Completed'
GROUP BY l.City, p.Date;

-- create view for top rating drivers according to reviews for each city
CREATE OR REPLACE VIEW vw_DriverLeaderboard AS
SELECT 
    l.City,
    u.Full_Name,
    d.Average_Rating,
    d.Total_Trips
FROM Driver d
JOIN User u ON d.driver_id = u.user_id
JOIN Rides r ON r.driver_id = d.driver_id
JOIN Location l ON r.pickup_loc_id = l.location_id
WHERE d.Verification_Status = 'Verified'
GROUP BY l.City, d.driver_id
ORDER BY l.City, d.Average_Rating DESC;

CREATE OR REPLACE VIEW vw_RevenueByMethod AS
SELECT Method, SUM(Amount) AS Total, COUNT(*) AS Transactions
FROM Payment WHERE Status = 'Completed'
GROUP BY Method;

CREATE OR REPLACE VIEW vw_Refunds AS
SELECT COUNT(*) AS Total_Refunds, SUM(Amount) AS Refund_Total
FROM Payment WHERE Status = 'Refunded';

CREATE OR REPLACE VIEW vw_DriverEarningsSummary AS
SELECT driver_id, SUM(gross_amount) AS Total_Gross,
       SUM(commission_amount) AS Total_Commission,
       SUM(net_amount) AS Net_Earnings
FROM DriverEarnings GROUP BY driver_id;

-- Roles to grant and revoke access
CREATE ROLE 'rider_role', 'driver_role', 'admin_role';

     -- admin has full control
GRANT ALL PRIVILEGES ON RideFlow.* TO 'admin_role';

    -- rider can request, pay , complaint and rate
GRANT SELECT, INSERT,Update ON RideFlow.Rides             TO 'rider_role';
GRANT SELECT, INSERT ON RideFlow.Payment           TO 'rider_role';
GRANT SELECT, UPDATE ON RideFlow.Wallet            TO 'rider_role';
GRANT INSERT         ON RideFlow.Rating            TO 'rider_role';
GRANT INSERT         ON RideFlow.Complaints        TO 'rider_role';
GRANT SELECT         ON RideFlow.PromoCode         TO 'rider_role';
GRANT SELECT, Insert         ON RideFlow.Location          TO 'rider_role';
GRANT SELECT         ON RideFlow.RideHistory       TO 'rider_role';


GRANT SELECT, UPDATE ON RideFlow.Driver            TO 'driver_role';
GRANT SELECT, UPDATE ON RideFlow.Rides             TO 'driver_role';
GRANT SELECT         ON RideFlow.Vehicle           TO 'driver_role';
GRANT SELECT         ON RideFlow.DriverEarnings    TO 'driver_role';
GRANT SELECT, INSERT ON RideFlow.Wallet            TO 'driver_role';
GRANT INSERT         ON RideFlow.PayoutRequest     TO 'driver_role';
GRANT INSERT         ON RideFlow.Rating            TO 'driver_role';
GRANT INSERT         ON RideFlow.Complaints        TO 'driver_role';
GRANT SELECT         ON RideFlow.RideHistory       TO 'driver_role';